### PR TITLE
EVM transactions improvements

### LINKED ISSUE #2937: Infinite loading on the Sign transaction button when you cancel permit sign
**Current:** https://jam.dev/c/94f4e8de-25bb-4776-bf19-1dbfc6d9c507

**Expected:** The error should appear - Error.Cancelled (the same behaviour when you cancel sign with the substrate wallet)

Image

### LINKED ISSUE #2955: EVM transaction is successful on FE, but fails on blockchain “OutOfGas: NULL”
This occurs only when the fee payment asset is WETH.
Examples:

- **You bought 0.00002 atBTC for 2.2366 USDT -** https://hydration.subscan.io/tx/0x3d2e83a3ca03452f088683e875bc1affd3a30961387d1f16955768d2b942e09b
- **You sold 1 USDT for 0.000008957 atBTC -** https://hydration.subscan.io/tx/0xbb784ba276f218bb98b4e3a20c33c5d0083a0adc3fbe4a9694e89ae06e0feaf3

### PR DESCRIPTION
**Pull request by jvonasek**
fixes #2955
fixes #2937

Better gas estimation based on extrinsic weight, should lead to better EVM functionality

### CODE REVIEW

File: apps/main/src/modules/transactions/review/ReviewTransactionStatus.tsx [hunk 1]
```diff
@@ -82,12 +85,53 @@ export const StatusText: React.FC<StatusBoxProps> = ({
...
+  const { t } = useTranslation()
+  const { copied, copy } = useCopy(5000)
+  const { account } = useAccount()
+  const { getAssetWithFallback } = useAssets()
+  const { tx, feeAssetId, error } = useTransaction()
+
+  const { data: chain } = useChainSpecData()
+  const { data: bestNumber } = useBestNumber()
+
+  const blockNumber = bestNumber?.parachainBlockNumber?.toString() ?? ""
```
Comment (radoslavcleevio) [inline apps/main/src/modules/transactions/review/ReviewTransactionStatus.tsx]: I would wrap this computation in a callback.

File: packages/web3-connect/src/wallets/BaseEIP1193Wallet/index.ts [hunk 2]
```diff
@@ -137,36 +116,29 @@ export class BaseEIP1193Wallet implements Wallet {
...
     }
 
-    this._extension.on("chainChanged", async (payload) => {
-      const chainId = typeof payload === "string" ? parseInt(payload) : null
-      callback?.(chainId)
-    })
+    this._extension.on("accountsChanged", handler)
+
+    return () => {
+      if (!this._extension) return
```
Comment (radoslavcleevio) [inline packages/web3-connect/src/wallets/BaseEIP1193Wallet/index.ts]: You should extract this at the beginning so that it will not (possibly) be changed when it is used in the unsubscribe. The check here does not make sense since we already subscribed.

File: packages/web3-connect/src/utils/wallet.ts [hunk 3]
```diff
@@ -75,3 +76,40 @@ export function getWalletModeFromAddress(address: string) {
 
   return null
 }
+
+export type AccountsSubscribeOptions = {
+  onDisconnect: () => void | Promise<void>
```
Comment (radoslavcleevio) [inline packages/web3-connect/src/utils/wallet.ts]: Do we really need promises here if we do not await anything?

File: packages/web3-connect/src/hooks/useWeb3Enable.ts [hunk 4]
```diff
@@ -59,6 +85,14 @@ export const useWeb3Enable = () => {
     },
   })
 
+  useEffect(() => {
+    const unsubs = unsubsRef.current
```
Comment (radoslavcleevio) [inline packages/web3-connect/src/hooks/useWeb3Enable.ts]: This should be accessed in the cleanup to be most up date.

Comment (jvonasek) [reply packages/web3-connect/src/hooks/useWeb3Enable.ts]: theres lint error saying not to do that
