### PR TITLE
Rework farm fetching, sort table by APY, fix fees

### LINKED ISSUE #1734: wrong LP fees
these are wrong
image
that's the LP fee on each trade, not the fees from LP fee
here you can see fee from LP fee
image
this appears to be showing the LP fee instead of fee from LP fee
image

### PR DESCRIPTION
**Pull request by vkulinich-cl**
Fix #1734

### CODE REVIEW

File: src/utils/constants.ts [hunk 1]
```diff
@@ -51,3 +51,5 @@ export const DOC_LINK = "https://docs.hydration.net"
 export const HYDRATION_PARACHAIN_ID = 2034
 export const HYDRATION_PARACHAIN_ADDRESS =
   "13cKp89Uh2yWgTG28JA1QEvPUMjEPKejqkjHKf9zqLiFKjH6"
+
+export const HOUR_STALE_TIME = 1000 * 60 * 60 * 1
```
Comment (jvonasek) [inline src/utils/constants.ts:55]: I would just call it HOUR_MS, since it could be used for other purpose than just stale time.

Or you can also import similar constants from date-fns
`import { millisecondsInHour } from "date-fns/constants"`
