### PR TITLE
Fix github issue #3616

### LINKED ISSUE #3616: UI leftover issues
- [ ] PRIME in MM: why there is N/A? + use shortcuts for millions

Image

- [ ] PRIME charts are not solved: https://discord.com/channels/882700370307067966/884910108180635689/1480891503860777091

- [ ] now volume seems too high: https://discord.com/channels/882700370307067966/884910108180635689/1481509638603280445

- [ ] wallet banner and chart + balance part: https://discord.com/channels/882700370307067966/884910108180635689/1482099156880461824

- [ ] APY is not already recalculated based on ratio in pool? https://discord.com/channels/882700370307067966/884910108180635689/1482165753292783710

### LINKED ISSUE #3638: Swap history (mrq)
- [ ] let me invert price in swap history
- [ ] recent pair -> current pair

### PR DESCRIPTION
**Pull request by vkulinich-cl**
Fix #3616
Fix #3638

### CODE REVIEW

File: apps/main/src/modules/borrow/reserve/components/ReserveSectionDivider.tsx [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { getToken } from "@galacticcouncil/ui/utils"
 export const ReserveSectionDivider = () => (
   <Box
     bg={getToken("surfaces.themeBasePalette.background")}
-    height={4}
+    height={1}
```
Comment (jvonasek) [inline apps/main/src/modules/borrow/reserve/components/ReserveSectionDivider.tsx]: I think we can just use `<Separator />`,

Also please add tokens instead of pixel values
```
mx="-xl"
my={["xl", "xxxl"]}
```

File: apps/main/src/modules/borrow/reserve/components/SupplyInfo.tsx [hunk 2]
```diff
@@ -45,34 +46,34 @@ export const SupplyInfo = ({
 
   return (
     <>
-      <Flex
+      <Stack
+        gap={[10, 40]}
```
Comment (jvonasek) [inline apps/main/src/modules/borrow/reserve/components/SupplyInfo.tsx]: please add tokens ["m", "xxxl"]

File: apps/main/src/modules/borrow/reserve/ReserveConfiguration.tsx [hunk 3]
```diff
@@ -51,7 +51,7 @@ export const ReserveConfiguration: React.FC<ReserveConfigurationProps> = ({
 
   return (
     <>
-      <Text fs="p3" fw={500} sx={{ mb: 30 }}>
+      <Text fs="p3" fw={500} sx={{ mb: [10, 30] }}>
```
Comment (jvonasek) [inline apps/main/src/modules/borrow/reserve/ReserveConfiguration.tsx]: use tokens

**Review by jvonasek — CHANGES_REQUESTED** [review]

**Review by jvonasek — APPROVED** [review]
