### PR TITLE
Estimate fees for stablepool + omnipool positions

### LINKED ISSUE #1447: "Add to Omnipool" UI is stuck
I was sending [this transaction](https://hydration.subscan.io/extrinsic/0xeaa807b95452b3086ecf851e40793adce58fd701725cf35a310f655c5c0ff2e4) and it failed. I assume it failed because I wanted to use all my assets and together with fees, the transaction was invalid because I didn't had enough funds? After sending the transaction, the UI was stuck as shown below in the image. Clicking on the close button did not worked. In the end I needed to reload the page.

image

### PR DESCRIPTION
**Pull request by jvonasek**
fixes #1447

### CODE REVIEW

File: src/sections/pools/modals/AddLiquidity/AddLiquidityForm.tsx [hunk 1]
```diff
@@ -59,6 +60,12 @@ export const AddLiquidityForm = ({
   const { poolShare, spotPrice, omnipoolFee, assetMeta, assetBalance } =
     useAddLiquidity(assetId, assetValue)
 
+  useEffect(() => {
+    if (initialAmount && assetBalance?.balance) {
+      form.trigger()
+    }
+  }, [assetBalance?.balance, form, initialAmount])
+
```
Comment (vkulinich-cl) [inline src/sections/pools/modals/AddLiquidity/AddLiquidityForm.tsx:68]: We don't need it anymore, it was fixed in another PR
